### ISSUE TITLE
Automodel generator not works on Centos 7 With Node.js version 6.9.5

### ISSUE THREAD

**Issue by 0xItamar** [cadrogui/sails-generator-automodel#3]
This is the error after:
1. git clone repo, link to npm
2. sails new app
3. cd app
4. sails generate automodel
Error: Cannot find module '../../config/connections'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/USER/Work/Sails/automodel/lib/discover.js:7:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by cadrogui** [comment]
Hi, all bugs are fixed in the new version, take a look to the readme for instructions, let me know if you have problems.

regards.

**Comment by 0xItamar** [comment]
Not fixed..
בתאריך יום ג׳, 28 בפבר 2017 ב-18:36 מאת Mikel Carozzi <
notifications@github.com>:
